// AUTO-GENERATED by scripts/generate-dictionary-indexes.ts - do not edit.
// Regenerated by the pre-hooks of dev/build/check/test:unit (npm run gen:dictionary).
import type { SignEntry } from '../../types.js';

import column from './01-column.js';
import dispersion from './02-dispersion.js';
import levitation from './03-levitation.js';
import pull from './04-pull.js';
import crush from './05-crush.js';
import float from './06-float.js';
import region from './07-region.js';
import convergence from './08-convergence.js';
import collection from './09-collection.js';
import billowing from './10-billowing.js';
import repetition from './11-repetition.js';
import weave from './12-weave.js';

const entries: readonly SignEntry[] = [
	column,
	dispersion,
	levitation,
	pull,
	crush,
	float,
	region,
	convergence,
	collection,
	billowing,
	repetition,
	weave
];

export default entries;
