// AUTO-GENERATED by scripts/generate-dictionary-indexes.ts - do not edit.
// Regenerated by the pre-hooks of dev/build/check/test:unit (npm run gen:dictionary).
import type { SigilEntry } from '../../types.js';

import fire from './01-fire.js';
import water from './02-water.js';
import windDirectsAir from './03-wind-directs-air.js';
import earth from './04-earth.js';
import light from './05-light.js';
import crystal from './06-crystal.js';
import aeriform from './07-aeriform.js';
import windUnderfoot from './08-wind-underfoot.js';

const entries: readonly SigilEntry[] = [
	fire,
	water,
	windDirectsAir,
	earth,
	light,
	crystal,
	aeriform,
	windUnderfoot
];

export default entries;
