/**
 * Regenerates src/lib/dictionary/{sigils,signs}/index.ts from the entry
 * modules in each folder, so adding a symbol file is enough to register it.
 * Wired into the pre-hooks of dev/build/check/test:unit; tests/dictionary.test.ts
 * fails when an index is stale.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const dictionaryDir = fileURLToPath(new URL('../src/lib/dictionary', import.meta.url));

const INDEX_TARGETS = [
	{ folder: 'sigils', entryType: 'SigilEntry' },
	{ folder: 'signs', entryType: 'SignEntry' }
];

function identifierFor(fileBaseName: string): string {
	return fileBaseName
		.replace(/^\d+-/, '')
		.replace(/-(\w)/g, (_, char: string) => char.toUpperCase());
}

function indexContent(folder: string, entryType: string): string {
	const moduleNames = readdirSync(join(dictionaryDir, folder))
		.filter((file) => file.endsWith('.ts') && file !== 'index.ts')
		.sort((left, right) => left.localeCompare(right, undefined, { numeric: true }))
		.map((file) => file.replace(/\.ts$/, ''));

	return [
		'// AUTO-GENERATED by scripts/generate-dictionary-indexes.ts - do not edit.',
		'// Regenerated by the pre-hooks of dev/build/check/test:unit (npm run gen:dictionary).',
		`import type { ${entryType} } from '../../types.js';`,
		'',
		...moduleNames.map((name) => `import ${identifierFor(name)} from './${name}.js';`),
		'',
		`const entries: readonly ${entryType}[] = [`,
		...moduleNames.map((name, index) => {
			const comma = index === moduleNames.length - 1 ? '' : ',';
			return `\t${identifierFor(name)}${comma}`;
		}),
		'];',
		'',
		'export default entries;',
		''
	].join('\n');
}

for (const { folder, entryType } of INDEX_TARGETS) {
	const indexPath = join(dictionaryDir, folder, 'index.ts');
	const next = indexContent(folder, entryType);
	const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : null;
	if (current !== next) {
		writeFileSync(indexPath, next);
		console.log(`regenerated ${folder}/index.ts`);
	}
}
